//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject_Iqbal.Models
{
    using MVCProject_Iqbal.CustomValidation;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ExamDetail
    {
        public int ExamDetailsID { get; set; }

        [Required(ErrorMessage = "This Field is Required!")]
        [StringLength(30, MinimumLength = 2, ErrorMessage = "You Must be Give Minimum 2 and Maximum 30 Chrecter")]
        public string ExamName { get; set; }

        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime ExamDate { get; set; }

        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [CustomHireDate(ErrorMessage = "Hire Date must be less than or equal to Today's Date")]
        public System.DateTime ResultPublishDate { get; set; }

        [Required(ErrorMessage = "This Field is Required!")]

        public int MCQ { get; set; }
        [Required(ErrorMessage = "This Field is Required!")]

        public int Descriptive { get; set; }
        [Required(ErrorMessage = "This Field is Required!")]

        public int Evidence { get; set; }
        public int TraineeID { get; set; }
        public Nullable<int> Total { get; set; }
    
        public virtual Trainee Trainee { get; set; }
    }
}
