//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject_Iqbal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Register
    {
        public int RegisterID { get; set; }
        [Required(ErrorMessage ="This Field is Required!!")]
        [StringLength(30, MinimumLength = 2, ErrorMessage = "You Must be Give Minimum 2 and Maximum 30 Chrecter")]
        public string FullName { get; set; }

        [Required(ErrorMessage = "This Field is Required!!")]
        public string FatherName { get; set; }

        [Required(ErrorMessage = "This Field is Required!!")]
        public string MotherName { get; set; }

        [Display(Name ="Email Address")]
        [DataType(DataType.EmailAddress)]
        [RegularExpression(@"^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$", ErrorMessage = "Invalid Email Address")]
        public string Email { get; set; }
        [Required(ErrorMessage = "This Field is Required!!")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "This Field is Required!!")]
        public string Password { get; set; }
    }
}
