//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject_Iqbal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Trainer
    {
        public int TrainerID { get; set; }
        [Required(ErrorMessage = "This Field is Required!")]

        public string TrainerName { get; set; }
        [Required(ErrorMessage = "This Field is Required!")]

        public decimal Salary { get; set; }
        public string Picture { get; set; }
        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; }
    }
}
